<?php

$market_research= [
    
        "Big Data" => "#",
        "Business Intelligence" => "#",
        "Data Science" => "#",
        "Others" => "#",
        "EdTech" => "#",
        "Online Classified" => "#",
        "Auto & Truck Manufacturers" => "#",
        "Auto, Truck & Motorcycle Parts" => "#",
        "Electric Vehicles" => "#",
        "Tires & Rubber Products" => "#",
        "Art" => "#",
        "Handicraft" => "#",
        "Photography" => "#",
        "Agricultural Chemicals" => "#",
        "Commodity Chemicals" => "#",
        "Diversified Chemicals" => "#",
        "Specialty Chemicals" => "#",
        "Integrated communication services" => "#",
        "Network Technology Solutions" => "#",
        "Wireless" => "#",
        "Construction & Engineering" => "#",
        "Construction Materials" => "#",
        "Construction Supplies & Fixtures" => "#",
        "Homebuilding" => "#",
        "New-age Construction Technologies" => "#",
        "Agri-Tech" => "#",
        "Animal Husbandry" => "#",
        "Dairy Farming" => "#",
        "Fisheries" => "#",
        "Food Processing" => "#",
        "Horticulture" => "#",
        "Organic Agriculture" => "#",
        "Aviation & Others" => "#",
        "Defence Equipment" => "#",
        "Drones" => "#",
        "Space Technology" => "#",
        "Machine Learning" => "#",
        "NLP" => "#",
        "Clean Tech" => "#",
        "Waste Management" => "#",
        "Event Management" => "#",
        "Weddings" => "#",
        "Apparel" => "#",
        "Fan Merchandise" => "#",
        "Fashion Technology" => "#",
        "Jewellery" => "#",
        "Lifestyle" => "#",
        "Accounting" => "#",
        "Advisory" => "#",
        "Billing and Invoicing" => "#",
        "Bitcoin and Blockchain" => "#",
        "Business Finance" => "#",
        "Crowdfunding" => "#",
        "Foreign Exchange" => "#",
        "Insurance" => "#",
        "Microfinance" => "#",
        "Mobile wallets Payments" => "#",
        "P2P Lending" => "#",
        "Payment Platforms" => "#",
        "Personal Finance" => "#",
        "Point of Sales" => "#",
        "Trading" => "#",
        "CXM" => "#",
        "Cloud" => "#",
        "Collaboration" => "#",
        "Customer Support" => "#",
        "ERP" => "#",
        "Enterprise Mobility" => "#",
        "Location Based" => "#",
        "SCM" => "#",
        "Food Technology/Food Delivery" => "#",
        "Microbrewery" => "#",
        "Restaurants" => "#",
        "Industrial Design" => "#",
        "Web Design" => "#",
        "Coaching" => "#",
        "E-learning" => "#",
        "Education Technology" => "#",
        "Skill Development" => "#",
        "Manufacture of Electrical Equipment" => "#",
        "Manufacture of Machinery and Equipment" => "#",
        "Renewable Energy Solutions" => "#",
        "Renewable Nuclear Energy" => "#",
        "Renewable Solar Energy" => "#",
        "Renewable Wind Energy" => "#",
        "3d printing" => "#",
        "Electronics" => "#",
        "Embedded" => "#",
        "Manufacturing" => "#",
        "Semiconductor" => "#",
        "Biotechnology" => "#",
        "Health & Wellness" => "#",
        "Healthcare IT" => "#",
        "Healthcare Services" => "#",
        "Healthcare Technology" => "#",
        "Medical Devices Biomedical" => "#",
        "Pharmaceutical" => "#",
        "Manufacturing & Warehouse" => "#",
        "Smart Home" => "#",
        "Wearables" => "#",
        "Application Development" => "#",
        "BPO" => "#",
        "IT Consulting" => "#",
        "IT Management" => "#",
        "KPO" => "#",
        "Product Development" => "#",
        "Project Management" => "#",
        "Testing" => "#",
        "Web Development" => "#",
        "Internships" => "#",
        "Recruitment Jobs" => "#",
        "Skills Assessment" => "#",
        "Talent Management" => "#",
        "Training" => "#",
        "Branding" => "#",
        "Digital Marketing (SEO Automation)" => "#",
        "Discovery" => "#",
        "Loyalty" => "#",
        "Market Research" => "#",
        "Sales" => "#",

        "Oil & Gas Drilling" => "#",
        "Oil & Gas Exploration and Production" => "#",
        "Oil & Gas Transportation Services" => "#",
        "Oil Related Services and Equipment" => "#",

        "Digital Media" => "#",
        "Digital Media Blogging" => "#",
        "Digital Media News" => "#",
        "Digital Media Publishing" => "#",
        "Digital Media Video" => "#",

        "Entertainment" => "#",
        "Movies" => "#",
        "OOH Media" => "#",
        "Social Media" => "#",
        "Comparison Shopping" => "#",
        "Retail Technology" => "#",
        "Social Commerce" => "#",

        "Baby Care" => "#",
        "Home Care" => "#",
        "Laundry" => "#",
        "Personal Care" => "#",

        "Business Support Services" => "#",
        "Business Support Supplies" => "#",
        "Commercial Printing Services" => "#",
        "Employment Services" => "#",
        "Environmental Services & Equipment" => "#",
        "Professional Information Services" => "#",

        "Fantasy Sports" => "#",
        "Sports Promotion and Networking" => "#",

        "Corporate Social Responsibility" => "#",
        "NGO" => "#",

        "Apparel & Accessories" => "#",
        "Leather Footwear" => "#",
        "Leather Textiles Goods" => "#",
        "Non-Leather Footwear" => "#",
        "Non-Leather Textiles Goods" => "#",

        "E-Commerce" => "#",
        "Education" => "#",
        "Media and Entertainment" => "#",
        "Natural Language Processing" => "#",

        "Utility Services" => "#",
        "Freight & Logistics Services" => "#",
        "Passenger Transportation Services" => "#",
        "Traffic Management" => "#",
        "Transport Infrastructure" => "#",

        "Experiential Travel" => "#",
        "Facility Management" => "#",
        "Holiday Rentals" => "#",
        "Hospitality" => "#",
        "Hotel" => "#",
        "Ticketing" => "#",
        "Wayside Amenities" => "#",

        "Cyber Security" => "#",
        "Home Security Solutions" => "#",
        "Public Citizen Security Solutions" => "#",

        "Coworking Spaces" => "#",
        "Housing" => "#",

        "Auto Vehicles, Parts & Service Retailers" => "#",
        "Computer & Electronics Retailers" => "#",
        "Home Furnishings Retailers" => "#",
        "Home Improvement Products & Services Retailers" => "#",

        "Personal Security" => "#",

        "Robotics Application" => "#",
        "Robotics Technology" => "#",

        "Physical Toys and Games" => "#",
        "Virtual Games" => "#",

        "Agnostic Sector" => "#",
        "Deep Tech" => "#",
        "Smart City" => "#",
        "Blockchain" => "#",
        "Digital Health" => "#",
        "Water and Sanitation" => "#",
        "Circular Economy" => "#",
        "Technology" => "#",
        "FMCG" => "#",
        "Data Analysis" => "#",
        "IoT" => "#",
        "Legal-Tech" => "#",
        "Unmanned Aerial Vehicles" => "#",
        "Infrastructure" => "#",
        "Edge Computing" => "#",
        "Child Protection" => "#",

        "Sustainable Blue Economy" => "#",
        "Ocean Engineering" => "#",
        "Marine Tourism" => "#",
        "Coastal Protection" => "#",
        "Ships and Ports Infrastructure" => "#",

        "Manufacturing and Allied Engineering Sectors" => "#",

        "Assistive Technology" => "#",
        "Assistance Technology" => "#",

        "IoT Machine Learning" => "#",
        "Smart Home Space Technology Wearables" => "#"
];


?>

<div class="page-body pt-1 px-2">
    <?php $this->load->view('map/header') ?>

    <h2 align="center" class="mt-4 mb-3">Market Research</h2>



    <div class="my-table overflow-scroll">
        <?php foreach ($market_research as $ministry => $link) { ?>
            <a href="<?= $link ?>">
                <div class="element">
                    <div class="name"><?= htmlspecialchars($ministry) ?></div>
                </div>
            </a>
        <?php } ?>
    </div>
</div>